// <auto-generated />
using System;
using HtmlToPdf.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HtmlToPdf.Migrations
{
    [DbContext(typeof(ConverterContext))]
    [Migration("20221031231427_IndexByOriginHash")]
    partial class IndexByOriginHash
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HtmlToPdf.Models.ConvertedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Origin")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("OriginHash")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OriginHash");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
